stages:
  - build
  - release

build:operator:
  stage: build
  image:
    name: golang:1.20.1-alpine3.16
  only:
    refs:
    - yd/v1.20.5/describe-node-listers
  artifacts:
    paths:
      - _output/bin/kubectl
  before_script:
    - apk add make bash rsync
  script:
    - make kubectl

build:release:
  stage: release
  image:
    name: node:18.14.2-alpine3.16
  only:
    refs:
    - yd/v1.20.5/describe-node-listers
  script:
  - npx semantic-release