branches:
- yd/v1.20.5/describe-node-listers
preset: "angular"
tagFormat: v1.20.5-enhanced-describe-v${version}
plugins:
- "@semantic-release/commit-analyzer"
repositoryUrl: "https://github.com/YitzyD/kubernetes.git"
analyzeCommits:
- path: "@semantic-release/commit-analyzer"
  releaseRules:
  - type: "feature"
    release: "minor"
  - type: "update"
    release: "minor"
  - type: "refactor"
    release: "patch"
  - type: "fix"
    release: "patch"
  - type: "docs"
    release: "patch"
  - type: chore
    release: "patch"
  parserOpts:
    noteKeywords:
    - "BREAKING CHANGE"
    - "BREAKING CHANGES"
publish:
- path: "@semantic-release/github"
  assets: 
    path: "_output/bin/kubectl"